# dataset directory
datasets_base_dir: ../datasets/
raw_datasets_dir:
  Jin2022: raw/Jin2022/
raw_network_datasets_dir:
  4G: raw_network/4G/

viewport_datasets_dir: 
  Jin2022: Jin2022/viewports/
video_datasets_dir:
  Jin2022: Jin2022/video_manifests/
network_datasets_dir:
  4G: network/4G

# result directory
results_base_dir: ../results/
vp_results_dir: viewport_prediction
bs_results_dir: bitrate_selection

# model directory
models_base_dir: ../models/
vp_models_dir: viewport_prediction
bs_models_dir: bitrate_selection

# enumerate datasets
datasets_list: ['Jin2022']
network_datasets_list: ['4G']

# video and dataset information
video_info:
  # video resolution are logicially regularized as 2560x1440 in other part of the codes for simplicity.
  Jin2022: 
    1: [60, 1280, 720]  # video length, video width, video height 
    2: [60, 1280, 720]  
    3: [60, 1280, 720]  
    4: [60, 1280, 720]  
    5: [60, 1280, 720]  
    6: [60, 1280, 720]  
    7: [60, 1280, 720]  
    8: [60, 1280, 720]  
    9: [58, 1280, 720]  
    10: [60, 1920, 1080]  
    11: [60, 1920, 1080]
    12: [60, 1920, 1080]
    13: [60, 1920, 1080]
    14: [60, 1920, 1080]
    15: [60, 1920, 1080]
    16: [60, 1920, 1080]
    17: [60, 1920, 1080]
    18: [58, 1920, 1080]
    19: [60, 2560, 1440]
    20: [60, 2560, 1440]
    21: [60, 2560, 1440]
    22: [60, 2560, 1440]
    23: [60, 2560, 1440]
    24: [60, 2560, 1440]
    25: [60, 2560, 1440]
    26: [60, 2560, 1440]
    27: [58, 2560, 1440]

video_num:
  Jin2022: 27

user_num: 
  Jin2022: 60  # for Jin2022 dataset, we only select 60 users for evaluation

# default tiling and video configuration
tile_num_width: 8
tile_num_height: 8
tile_total_num: 64
video_width: 2560  # unified video width
video_height: 1440  # unified video height

chunk_length: 1
video_rates: [1, 5, 8, 16, 35]

# network dataset information
network_info:
  4G:
    0: report_bicycle_0001.pkl
    1: report_bicycle_0002.pkl
    2: report_bus_0001.pkl
    3: report_bus_0002.pkl
    4: report_bus_0003.pkl
    5: report_bus_0004.pkl
    6: report_bus_0005.pkl
    7: report_bus_0006.pkl
    8: report_bus_0007.pkl
    9: report_bus_0008.pkl
    10: report_bus_0009.pkl
    11: report_bus_0010.pkl
    12: report_bus_0011.pkl
    13: report_car_0001.pkl
    14: report_car_0002.pkl
    15: report_car_0003.pkl
    16: report_car_0004.pkl
    17: report_car_0005.pkl
    18: report_car_0006.pkl
    19: report_car_0007.pkl
    20: report_car_0008.pkl
    21: report_foot_0001.pkl
    22: report_foot_0002.pkl
    23: report_foot_0003.pkl
    24: report_foot_0004.pkl
    25: report_foot_0005.pkl
    26: report_foot_0006.pkl
    27: report_foot_0007.pkl
    28: report_foot_0008.pkl
    29: report_train_0001.pkl
    30: report_train_0002.pkl
    31: report_train_0003.pkl
    32: report_tram_0001.pkl
    33: report_tram_0002.pkl
    34: report_tram_0003.pkl
    35: report_tram_0004.pkl
    36: report_tram_0005.pkl
    37: report_tram_0006.pkl
    38: report_tram_0007.pkl
    39: report_tram_0008.pkl


# dataset split information
network_split:
  4G:
    train: [26, 24, 4, 9, 39, 29, 30, 1, 12, 10, 2, 3, 25, 14, 15, 0, 36, 17, 8, 19, 11, 35, 21, 5]
    valid: [22, 32, 7, 20, 18, 6, 38, 37]
    test: [31, 33, 16, 23, 13, 28, 27, 34]

video_split:
  Jin2022:
    train: [1, 2, 3, 4, 6, 8, 9, 10, 11, 13, 15, 17, 18, 19, 20, 22, 23, 24]
    valid: [12, 5, 7,]
    test: [21, 14, 16,]
    
user_split:
  Jin2022:
    train: [22, 27, 30, 39, 44, 57, 59, 1, 9, 16, 20, 21, 46, 48, 51, 53, 2, 5, 6, 7, 12, 19, 25, 26, 28, 33, 36, 38, 47, 8, 15, 18, 29, 31, 34, 35, 41, 45, 49, 50, 54, 4, 17, 37, 43]
    valid: [22, 27, 30, 39, 44, 57, 59, 1, 9, 16, 20, 21, 46, 48, 51, 53, 2, 5, 6, 7, 12, 19, 25, 26, 28, 33, 36, 38, 47, 8, 15, 18, 29, 31, 34, 35, 41, 45, 49, 50, 54, 4, 17, 37, 43]
    test: [3, 10, 14, 24, 32, 40, 52, 55, 58, 60, 11, 13, 23, 42, 56]

qoe_split:
  train: [[7, 1, 1], [1, 7, 1], [1, 1, 7], [3, 3, 3]]  # preference for viewport quality, rebuffering time and quality variation (preference weights are normalized in the codes)
  valid: [[7, 1, 1], [1, 7, 1], [1, 1, 7], [3, 3, 3]]
  test: [[5, 1, 3], [2, 4, 3], [1, 3, 5], [4, 4, 1]]

# viewport dataset sampling configuration
trim_head: 15
trim_tail: 15
frequency: 5
sample_step: 5

# video streaming configuration
startup_download: 5
max_size: 500000
max_throughput: 5000000
past_k: 8
action_space: 15